### ISSUE TITLE
Is this the issue?

### ISSUE THREAD

**Issue by timunie** [jaeaton/ECWP-Winch-Data#3]
https://github.com/jaeaton/ECWP-Winch-Data/blob/e7109c7a742a3df2856686c7598b45d18c69d878/ECWP_Data_Programe_Ava/Views/PlottingView.axaml#L14

This control is inside an ItemsControl. ItemsControl has a StackPanel internally, which will stick Items below each other. So it does not have a limited height and thus, GridSize * will not work as expected. Give this control a specific height and observe the result.

**Comment by jaeaton** [comment]
Tim,

This helps me understand it better. I did notice that fixing the size of the grid that holds the plot increased the size of the resultant plot. However it then requires a scroll view to see multiple plots.

My desired behavior would could be described as a stack panel that maximized the size of each panel. So if a single plot was chosen it would fill the entire area. If two were chosen it would divide it in half, etc.

I don't know enough to know where to look.

I appreciate your patience.

Josh

From: Tim ***@***.***>
Sent: Wednesday, March 15, 2023 5:07 PM
To: jaeaton/ECWP-Winch-Data ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jaeaton/ECWP-Winch-Data] Is this the issue? (Issue #3)


https://github.com/jaeaton/ECWP-Winch-Data/blob/e7109c7a742a3df2856686c7598b45d18c69d878/ECWP_Data_Programe_Ava/Views/PlottingView.axaml#L14<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjaeaton%2FECWP-Winch-Data%2Fblob%2Fe7109c7a742a3df2856686c7598b45d18c69d878%2FECWP_Data_Programe_Ava%2FViews%2FPlottingView.axaml%23L14&data=05%7C01%7Cjeaton%40whoi.edu%7C26bcc04db5934d58374d08db259927a4%7Cd44c5cc6d18c46cc8abd4fdf5b6e5944%7C0%7C0%7C638145111972860200%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pNn4Rf6vvGrpHEMqYpqx9RindpkSoeF7qxc6JdVmUgY%3D&reserved=0>

This control is inside an ItemsControl. ItemsControl has a StackPanel internally, which will stick Items below each other. So it does not have a limited height and thus, GridSize * will not work as expected. Give this control a specific height and observe the result.

-

**Comment by timunie** [comment]
Yeah honestly I still don't quite understand the desired output, but I assume you want several items below each other without a ScrollViewer at all. One Option I see is to use a  `UniformGrid` as ItemsControl.ItemPanel and remove the ScrollViewer completely. But this will require that you bind `UnifromGrid.Rows` to `Items.Count`. Also when you have too many items information may be missing. Anyway, Here is some sample code. 

```xml
<ItemsControl Items="{Binding TestItems}" >
    <ItemsControl.ItemTemplate>
        <DataTemplate>
           [Up to you]
        </DataTemplate>
    </ItemsControl.ItemTemplate>
    <ItemsControl.ItemsPanel>
        <ItemsPanelTemplate>
            <UniformGrid Rows="{Binding TestItems.Count}"></UniformGrid>
        </ItemsPanelTemplate>
    </ItemsControl.ItemsPanel>
</ItemsControl>
```
